---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release

on:
  create:
    tags:
      - 'v*'
    branches:
      - master
      - main

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    env:
      COSIGN_EXPERIMENTAL: "true"
      COSIGN_YES: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Cosign
      - uses: sigstore/cosign-installer@main

      # Install Crane
      - uses: imjasonh/setup-crane@v0.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Artifact
        run: |
          docker pull ghcr.io/xunholy/${{ github.event.repository.name }}/example:${{ github.sha }}
          docker tag ghcr.io/xunholy/${{ github.event.repository.name }}/example:${{ github.sha }} ghcr.io/xunholy/${{ github.event.repository.name }}/example:prod-${{ github.sha }}
          docker push ghcr.io/xunholy/${{ github.event.repository.name }}/example:prod-${{ github.sha }}

      - name: Get the digest of the OCI artifact
        id: crane
        run: |
          DIGEST=$(crane digest ghcr.io/xunholy/${{ github.event.repository.name }}/example:prod-${{ github.sha }})
          echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT

      - name: Verify Attestations
        run: |
          echo "Checking Attestations"
          cosign verify-attestation ghcr.io/xunholy/${{ github.event.repository.name }}/example@${{ steps.crane.outputs.DIGEST }} \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            --certificate-identity https://github.com/xUnholy/secure-software-supply-chain-demo/.github/workflows/build.yaml@refs/heads/main

      # Cosign the OCI artifact
      - name: Sign the OCI artifact [PROD]
        run: cosign sign ghcr.io/xunholy/${{ github.event.repository.name }}/example@${{ steps.crane.outputs.DIGEST }} -y
